CREATE DATABASE SENGroup25DB
ON PRIMARY
(
NAME= EdenFarmsDBData,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.mdf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
LOG ON
(
NAME= EdenFarmsDBLogs,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.ldf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
GO
USE SENGroup25DB
GO
CREATE Table tblClient
(
ClientID VARCHAR(30) PRIMARY KEY NOT NULL,
ClientName VARCHAR(30)NOT NULL,
ClientSurname VARCHAR(30)NOT NULL,
ClientAddress VARCHAR(100) NOT NULL, 
Email VARCHAR(50),
ContactNumber VARCHAR(12)
)
GO 
CREATE Table tblEmployee
(
EmpID VARCHAR(30) PRIMARY KEY NOT NULL,
ContractID INT FOREIGN KEY REFERENCES tblContract(ContractID),
EmpName VARCHAR(30) NOT NULL,
EmpSurname VARCHAR(30) NOT NULL, 
VatIDNumber VARCHAR(10) NOT NULL,
ContactNumber VARCHAR(12) NOT NULL,
Email VARCHAR(50) NOT NULL
);
GO
CREATE Table tblJob
(
JobID VARCHAR(30) PRIMARY KEY NOT NULL,
ClientID INT FOREIGN KEY REFERENCES tblClient(ClientID),
EmpID INT FOREIGN KEY REFERENCES tblEmployee(EmpID),
JobDescription VARCHAR(100) NOT NULL,
JobType VARCHAR(10) NOT NULL,
JobStatus VARCHAR(10) NOT NULL
)
GO
CREATE Table tblSkills
(
SkillID VARCHAR(30) PRIMARY KEY NOT NULL,
SkillDescription VARCHAR(80) NOT NULL,
SkillType VARCHAR(10) NOT NULL
)
GO
CREATE Table tblEmployeeSkills
(
EmpID VARCHAR(30) FOREIGN KEY REFERENCES tblEmployee(EmpID),
SkillID VARCHAR(30) FOREIGN KEY REFERENCES tblSkills(SkillID)
)
GO 
CREATE Table tblContract
(
ContractID VARCHAR(30) PRIMARY KEY NOT NULL,
ServiceLevel VARCHAR(20),
ExperationDate DATE
)
GO
CREATE Table tblEquipment
(
EquipmentID VARCHAR(30) PRIMARY KEY NOT NULL,
)
GO 
CREATE Table tblJobEquipment
(
EquipmentID VARCHAR(30) FOREIGN KEY REFERENCES tblEquipment(EquipmentID),
JobID VARCHAR(30) FOREIGN KEY REFERENCES tblJob(JobID)
)