CREATE DATABASE SENGroup25DB
ON PRIMARY
(
NAME= EdenFarmsDBData,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.mdf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
LOG ON
(
NAME= EdenFarmsDBLogs,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.ldf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
GO
USE SENGroup25DB
GO
CREATE Table tblClient
(
ClientID INT IDENTITY PRIMARY KEY,
ClientName VARCHAR(30)NOT NULL,
ClientSurname VARCHAR(30)NOT NULL,
ClientAddress VARCHAR(100) NOT NULL, 
Email VARCHAR(50),
ContactNumber VARCHAR(12)
)
GO 
CREATE Table tblEmployee
(
EmpID INT IDENTITY PRIMARY KEY,
ContractID INT FOREIGN KEY REFERENCES tblContract(ContractID),
EmpName VARCHAR(30) NOT NULL,
EmpSurname VARCHAR(30) NOT NULL, 
VatIDNumber VARCHAR(10) NOT NULL,
ContactNumber VARCHAR(12) NOT NULL,
Email VARCHAR(50) NOT NULL
);
GO
CREATE Table tblJob
(
JobID INT IDENTITY PRIMARY KEY,
ClientID INT FOREIGN KEY REFERENCES tblClient(ClientID),
EmpID INT FOREIGN KEY REFERENCES tblEmployee(EmpID),
JobDescription VARCHAR(100) NOT NULL,
JobType VARCHAR(10) NOT NULL,
JobStatus VARCHAR(10) NOT NULL
)
GO
CREATE Table tblSkills
(
SkillID INT IDENTITY PRIMARY KEY,
SkillDescription VARCHAR(80) NOT NULL,
SkillType VARCHAR(10) NOT NULL
)
GO
CREATE Table tblEmployeeSkills
(
EmpID INT FOREIGN KEY REFERENCES tblEmployee(EmpID),
SkillID INT FOREIGN KEY REFERENCES tblSkills(SkillID)
)
GO 
CREATE Table tblContract
(
ContractID INT IDENTITY PRIMARY KEY,
ServiceLevel VARCHAR(20),
ExperationDate DATE
)
GO
CREATE Table tblEquipment
(
EquipmentID INT IDENTITY PRIMARY KEY,
)
GO 
CREATE Table tblJobEquipment
(
EquipmentID INT FOREIGN KEY REFERENCES tblEquipment(EquipmentID),
JobID INT FOREIGN KEY REFERENCES tblJob(JobID)
)