CREATE DATABASE SENGroup25DB
ON PRIMARY
(
NAME= SENGroup25DBData,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.mdf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
LOG ON
(
NAME= SENGroup25DBLogs,
FILENAME= 'D:\Documents\Database\SEN\SENGroup25DB.ldf',
SIZE= 20MB,
FILEGROWTH= 10%,
MAXSIZE= 10GB
)
GO
USE SENGroup25DB
GO 
CREATE Table tblContract
(
ContractID VARCHAR(30) PRIMARY KEY NOT NULL,
ServiceLevel VARCHAR(20) NOT NULL,
ExperationDate VARCHAR(30) NOT NULL
)
GO
CREATE Table tblClient
(
ClientID VARCHAR(30) PRIMARY KEY NOT NULL,
ContractID VARCHAR(30) FOREIGN KEY REFERENCES tblContract(ContractID),
ClientPassword VARCHAR(30) NOT NULL,
ClientName VARCHAR(30) NOT NULL,
ClientSurname VARCHAR(30) NOT NULL,
ClientAddress VARCHAR(100) NOT NULL, 
Email VARCHAR(50) NOT NULL,
ContactNumber VARCHAR(12) NOT NULL
)
GO 
CREATE Table tblEmployee
(
EmpID VARCHAR(30) PRIMARY KEY NOT NULL,
EmpName VARCHAR(30) NOT NULL,
EmpSurname VARCHAR(30) NOT NULL, 
EmpPassword VARCHAR(30) NOT NULL,
VatIDNumber VARCHAR(10) NOT NULL,
ContactNumber VARCHAR(12) NOT NULL,
Email VARCHAR(50) NOT NULL
);
GO
CREATE Table tblJob
(
JobID VARCHAR(30) PRIMARY KEY NOT NULL,
ClientID VARCHAR(30) FOREIGN KEY REFERENCES tblClient(ClientID),
EmpID VARCHAR(30) FOREIGN KEY REFERENCES tblEmployee(EmpID),
JobDescription VARCHAR(100) NOT NULL,
JobType VARCHAR(15) NOT NULL,
JobStatus VARCHAR(15) NOT NULL
)
GO
CREATE Table tblSkill
(
SkillID VARCHAR(30) PRIMARY KEY NOT NULL,
SkillDescription VARCHAR(80) NOT NULL,
SkillType VARCHAR(15) NOT NULL
)
GO
CREATE Table tblEmployeeSkill
(
EmpID VARCHAR(30) FOREIGN KEY REFERENCES tblEmployee(EmpID) NOT NULL,
SkillID VARCHAR(30) FOREIGN KEY REFERENCES tblSkill(SkillID)  NOT NULL
)
GO
CREATE Table tblEquipment
(
EquipmentID VARCHAR(30) PRIMARY KEY NOT NULL,
EquipmentDescription VARCHAR(80) NOT NULL
)
GO 
CREATE Table tblJobEquipment
(
EquipmentID VARCHAR(30) FOREIGN KEY REFERENCES tblEquipment(EquipmentID) NOT NULL,
JobID VARCHAR(30) FOREIGN KEY REFERENCES tblJob(JobID) NOT NULL
)